import {ID,DISTANCES} from '../config.mjs';import {compareNaval,navalDamage,pursuit} from '../rules/naval.mjs';import {ChallengeApp} from './challenge.mjs';import {prompt,select,check,field} from '../utils/ui.mjs';
const {ApplicationV2,HandlebarsApplicationMixin}=foundry.applications.api;
export class NavalApp extends HandlebarsApplicationMixin(ApplicationV2){
 constructor(actor){super();this.actor=actor;this.hook=Hooks.on('updateActor',a=>{if(a.uuid===actor.uuid)this.render();});}
 static DEFAULT_OPTIONS={classes:['ea-app'],position:{width:670,height:610},window:{title:'Consola del Surcazul',resizable:true},actions:{configure:NavalApp.configure,navigate:NavalApp.navigate,maneuver:NavalApp.maneuver,fire:NavalApp.fire,resolve:NavalApp.resolve,board:NavalApp.board}};
 static PARTS={body:{template:'systems/eterno-azul/templates/applications/naval.hbs',scrollable:['']}};
 async _prepareContext(){const s=this.actor.system;const rival=s.naval.opponentUuid?await fromUuid(s.naval.opponentUuid):null;return {name:this.actor.name,system:s,rival:rival?.name??'Sin rival seleccionado',distance:DISTANCES[s.naval.distance],distances:DISTANCES.map((name,i)=>({name,active:i===s.naval.distance})),ammo:this.actor.items.filter(i=>i.type==='municion').reduce((n,i)=>n+i.system.quantity,0)};}
 async close(o){Hooks.off('updateActor',this.hook);return super.close(o);}
 static async configure(){if(!this.actor.isOwner)return;const s=this.actor.system;const f=await prompt('Situación naval',select('opponent','Navío rival',game.actors.filter(a=>a.type==='surcazul'&&a.uuid!==this.actor.uuid).map(a=>[a.uuid,a.name]),s.naval.opponentUuid)+select('distance','Distancia',DISTANCES.map((n,i)=>[i,n]),s.naval.distance)+check('pursuer','Somos los perseguidores',s.naval.pursuer)+check('moored','Amarrados con garfios',s.naval.moored));if(f)await this.actor.update({'system.naval':{...s.naval.toObject(),opponentUuid:f.get('opponent')??'',distance:Number(f.get('distance')),pursuer:f.has('pursuer'),moored:f.has('moored')}});}
 async pilot(){const f=await prompt('Buscador al mando',select('actor','Tripulante',game.actors.filter(a=>a.type==='buscador'&&a.isOwner).map(a=>[a.id,a.name])));return f?game.actors.get(f.get('actor')):null;}
 async contest(kind){const pilot=await this.pilot();if(!pilot)return;const rival=await fromUuid(this.actor.system.naval.opponentUuid);if(!rival)throw new Error('Selecciona un navío rival');const key=kind==='maneuver'?'maneuver':'sail';new ChallengeApp(pilot,'navegar',{shifts:compareNaval(this.actor.system[key],[rival.system[key]],{maneuver:kind==='maneuver'}),context:`${kind==='maneuver'?'Maniobra':'Persecución'} · ${this.actor.name}`}).render({force:true});}
 static async navigate(){try{await this.contest('pursuit');}catch(e){ui.notifications.warn(e.message);}}
 static async maneuver(){try{await this.contest('maneuver');}catch(e){ui.notifications.warn(e.message);}}
 static async fire(){try{const s=this.actor.system;if(s.naval.distance>=3)throw new Error('Los cañones no alcanzan esta distancia');if(!this.actor.items.some(i=>i.type==='municion'&&i.system.quantity>0))throw new Error('No queda munición');const pilot=await this.pilot();if(!pilot)return;const rival=await fromUuid(s.naval.opponentUuid);if(!rival)throw new Error('Selecciona un rival');new ChallengeApp(pilot,'combatir',{risk:rival.system.maneuver,context:`Artillería · ${this.actor.name}`}).render({force:true});}catch(e){ui.notifications.warn(e.message);}}
 static async resolve(){if(!this.actor.isOwner)return;try{const s=this.actor.system;const f=await prompt('Aplicar resultado naval',select('kind','Operación',[['pursuit','Persecución'],['fire','Calcular daño de artillería']])+field('successes','Éxitos del Desafío',0,'number')+field('risk','Riesgo del Desafío',1,'number')+check('consequence','Aceptamos una consecuencia adicional')+select('arc','Batería',[['broadside','Babor / estribor'],['bow','Proa'],['stern','Popa']]));if(!f)return;const successes=Number(f.get('successes')),risk=Number(f.get('risk'));if(f.get('kind')==='pursuit'){const distance=pursuit({...s.naval.toObject(),successes,risk,consequence:f.has('consequence')});await this.actor.update({'system.naval.distance':distance});}else{const n=navalDamage(s.power,Math.max(0,successes-risk),s.naval.distance,f.get('arc'),successes);ui.notifications.info(`Daño total: ${n}. Distribúyelo entre objetivos y aplícalo con Gestionar daño. La munición solo se pierde por consecuencias.`);}}catch(e){ui.notifications.warn(e.message);}}
 static async board(){ui.notifications.info(this.actor.system.naval.distance===0?'Acordad el abordaje con la DJ. Registra los amarres si usáis garfios.':'Debéis llegar a distancia de abordaje.');}
}
